# Generated by Django 2.1.5 on 2019-02-11 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20190211_0316'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='seats',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='tnumber',
        ),
    ]
